[package]
name = "lumina_game"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29.15", default-features = false, features = ["rwh_05"] }
lumina_engine = { path = "../engine" }

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.29.15", default-features = false, features = [
  "android-native-activity",
  "rwh_05",
] }
android_logger = "0.13.3"
log = "0.4.21"

[[bin]]
name = "lumina_game"
path = "src/main.rs"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
